package main

import (
	"context"
	"fmt"
	"log"
	"net/http"

	greetv1 "example/gen/greet/v1"        // generated by protoc-gen-go
	"example/gen/greet/v1/greetv1connect" // generated by protoc-gen-connect-go

	"connectrpc.com/connect"
	"connectrpc.com/otelconnect"
	"connectrpc.com/validate"
)

type GreetServer struct{}

func (s *GreetServer) Greet(
	_ context.Context,
	req *greetv1.GreetRequest,
) (*greetv1.GreetResponse, error) {
	res := &greetv1.GreetResponse{
		Greeting: fmt.Sprintf("Hello, %s!", req.Name),
	}
	log.Println("Greet request:", req.Name, "response:", res.Greeting)
	return res, nil
}

func (s *GreetServer) Header(
	_ context.Context,
	req *greetv1.HeaderRequest,
) (*greetv1.HeaderResponse, error) {
	result := req.RequestId + 1
	log.Println("Header request_id:", req.RequestId, "response_id:", result)
	return &greetv1.HeaderResponse{
		RequestId: result,
	}, nil
}

func (s *GreetServer) Profile(
	_ context.Context,
	_ *greetv1.ProfileRequest,
) (*greetv1.ProfileResponse, error) {
	log.Println("Profile request received")
	return &greetv1.ProfileResponse{
		Name:        "Jane Doe",
		PhoneNumber: "+1-555-0100",
		Email:       "jane@example.com",
	}, nil
}

func main() {
	otelInterceptor, err := otelconnect.NewInterceptor()
	if err != nil {
		log.Fatal(err)
	}
	greeter := &GreetServer{}
	mux := http.NewServeMux()

	path, handler := greetv1connect.NewGreetServiceHandler(
		greeter,
		// Validation via Protovalidate is almost always recommended
		connect.WithInterceptors(validate.NewInterceptor()),
		connect.WithInterceptors(otelInterceptor),
	)

	mux.Handle(path, handler)
	p := new(http.Protocols)
	p.SetHTTP1(true)
	// Use h2c so we can serve HTTP/2 without TLS.
	p.SetUnencryptedHTTP2(true)
	s := http.Server{
		Addr:      "localhost:8080",
		Handler:   mux,
		Protocols: p,
	}
	fmt.Println("Server started")
	s.ListenAndServe()

}
